@extends('layouts.app')
@section('title', 'داشبورد | reyhanTunell')
@section('page-title', 'داشبورد')
@section('content')
<div class="rt-page-heading"><div><h1>مدیریت تونل‌ها</h1><p>وضعیت سرویس‌ها و تونل‌های reyhanTunell را در یک نگاه ببینید.</p></div><button class="rt-primary-button" type="button">+ افزودن تونل</button></div>
<section class="rt-stats-grid" aria-label="آمار کلی">@foreach ($stats as $stat)<article class="rt-card rt-stat-card"><div class="rt-stat-label">{{ $stat['label'] }}</div><div class="rt-stat-value">{{ $stat['value'] }}</div><div class="rt-stat-icon rt-icon-{{ $stat['icon'] }}"></div></article>@endforeach</section>
<section class="rt-dashboard-grid"><article class="rt-card rt-activity-card"><div class="rt-card-heading"><h2>فعالیت اخیر</h2><span>امروز</span></div><div class="rt-activity-list">@foreach ($activities as $activity)<div class="rt-activity-item"><span class="rt-activity-dot"></span><div><strong>{{ $activity }}</strong><small>چند دقیقه قبل</small></div></div>@endforeach</div></article>
<article class="rt-card rt-table-card"><div class="rt-card-heading"><h2>تونل‌های اخیر</h2><a href="#">مشاهده همه</a></div><div class="rt-table-wrap"><table class="rt-table"><thead><tr><th>نام</th><th>پروتکل</th><th>وضعیت</th><th>عملیات</th></tr></thead><tbody>@foreach ($tunnels as $tunnel)<tr><td>{{ $tunnel['name'] }}</td><td>{{ $tunnel['protocol'] }}</td><td><span class="rt-status {{ $tunnel['status'] === 'فعال' ? 'is-online' : 'is-offline' }}">{{ $tunnel['status'] }}</span></td><td><button class="rt-more" type="button">•••</button></td></tr>@endforeach</tbody></table></div></article></section>
<section class="rt-card rt-health-card"><div class="rt-card-heading"><h2>سلامت سیستم</h2><span class="rt-health-live"><span class="rt-dot"></span> پایدار</span></div><div class="rt-health-grid">@foreach ($health as $metric)<div class="rt-health-item"><span>{{ $metric['label'] }}</span><strong>{{ $metric['value'] }}</strong></div>@endforeach</div></section>
@endsection
